### ISSUE TITLE
About thread safety

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_io#6]
This is just a question more than an issue.

I would like to clarify what the behaviour will be, if there are multiple threads that try to, say, pipeTo a sink at the same time?

**Comment by back2dos** [comment]
Piping to the same sink is not really meaningful, because the data is then randomly scattered (although I must admit, I don't know how nodejs will actually handle this, so if you pipe multiple NodeSources to NodeSinks it may wind up in order). If you want to pipe multiple sources onto the same sink, it's best to `append` them in the order you wish. The resulting `CompoundSource` still [uses the individual `pipeTo` implementations](https://github.com/haxetink/tink_io/blob/master/src/tink/io/Source.hx#L357), so the overhead should be minimal.

As for thread safety itself, it is limited. I'm not sure how to go about it. 

If you need safe concurrency, then the intended usage is with tink_runloop, which makes the [default worker be a runloop worker](https://github.com/haxetink/tink_io/blob/master/src/tink/io/Worker.hx#L5), and because meaning that read actions are [queued for execution in isolation](https://github.com/haxetink/tink_io/blob/master/src/tink/io/Source.hx#L288) - which is also true for reads.

Unfortunately, this safety does not extend to all sources / sinks.

A simple way of achieving it though would be something like this:

``` haxe
class IsolatedSource extends SourceBase {
  var target:Source;
  var worker:Worker;
  override public function read(into:Buffer, max:Int = 1 << 30)
    return worker.work(function () return target.read(into, max)).flatten();
  //..
}
```

That way you get the same kind of isolation.

**Comment by kevinresol** [comment]
Haven't got time to read your explanation yet. But let me just supplement a bit about my question. I am using a tink tcp connection to connect to db. Because all request and response will be through that connection, I wonder what will happen if multiple requests try to pipe into the connection's sink.

Other options would be to queue the requests manually or use one (pooled) connection for each request.

I will have a deeper look.

**Comment by kevinresol** [comment]
Or I should look into tink_streams?

**Comment by back2dos** [comment]
I'm afraid that the real answer to this question is: it depends on too many factors to specify.

As for properly sequencing pipes, this is not really thread-safety related.

We could add something like this:

``` haxe
class PipeSequencer {
  public function new(target:Sink):Void;
  public function pipe(source:Source, ?whenReady:Void->Bool):Future<PipeResult>;//if you return false when the sequencer is ready, the source gets skipped
}
```

Is that what you're looking for?

**Comment by back2dos** [comment]
Ok, I guess I would answer this way:

1. Sources can be concatenated and then piped to a sink (which is probably the most meaningful way to write multiple sources to one sink)
2. In multi-threaded environments, the operation on the underlying source/sink is executed by its worker. The default worker implementation is thread safe: a runloop worker, that queues ops and executes all of them on the same thread
